### ISSUE TITLE
Page "Häufig gestellte Fragen" not found

### ISSUE THREAD

**Issue by melwinm** [calderacc/criticalmass-in#146]
@maltehuebner see: https://criticalmass.in/content/faq

> Oops! An Error Occurred
> 
> The server returned a "404 Not Found".
> 
> Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by maltehuebner** [comment]
Fixed in #150
