### ISSUE TITLE
Clicking on `Edit City Name` while not being logged in results in HTTP 500 Status Code

### ISSUE THREAD

**Issue by Dumbaz** [calderacc/criticalmass-in#238]
In my case the link was `https://criticalmass.in/ulm-neu-ulm/edit`.
It works when logged in, but when not logged in, it results in 

`https://criticalmass.in/ulm-neu-ulm/edit`
```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

Expected Behaviour: It leads to the login page and asks to log in first

**Comment by maltehuebner** [comment]
Thanks for your report. I fixed this issue in #245.
