### ISSUE TITLE
Foto unter falscher Stadt gepostet...Rendsburg statt Rheine..wie löschen??

### ISSUE THREAD

**Issue by B0chumer** [calderacc/criticalmass-in#631]

**Comment by maltehuebner** [comment]
Ich lade nachher einfach mal ein anderes Foto dort hoch — an diesen Fall habe ich noch gar nicht gedacht 😄

**Comment by B0chumer** [comment]
...man könnte das Foto natürlich auch e7nfach nach Rheine umbuchen.🚴‍♂️☔Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Malte Hübner <notifications@github.com> Datum: 05.03.20  08:06  (GMT+01:00) An: calderacc/criticalmass-in <criticalmass-in@noreply.github.com> Cc: B0chumer <rainer.m.steinert@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [calderacc/criticalmass-in] Foto unter falscher Stadt gepostet...Rendsburg statt Rheine..wie löschen?? (#631) Ich lade nachher einfach mal ein anderes Foto dort hoch — an diesen Fall habe ich noch gar nicht gedacht 😄



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/calderacc/criticalmass-in/issues/631?email_source=notifications\u0026email_token=AOWMUAREAQKVBDBJMBEVGMLRF5FOPA5CNFSM4K7E6MFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEN37B4Y#issuecomment-595063027",

"url": "https://github.com/calderacc/criticalmass-in/issues/631?email_source=notifications\u0026email_token=AOWMUAREAQKVBDBJMBEVGMLRF5FOPA5CNFSM4K7E6MFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEN37B4Y#issuecomment-595063027",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
