### ISSUE TITLE
Datepicker not fully visible

### ISSUE THREAD

**Issue by thko11** [calderacc/criticalmass-in#632]
The map hides a part of datepicker on edit tour page:

https://criticalmass.in/torun/2020-03-21/edit

![Screenshot from 2020-03-02 13-22-34](https://user-images.githubusercontent.com/61693441/75677193-2a69ae80-5c8b-11ea-9220-5f99efa12dca.png)

**Comment by maltehuebner** [comment]
Thanks for reporting. It should be fixed in #638.
