### ISSUE TITLE
Live Tracking not visualized well for large groups with lots of noise

### ISSUE THREAD

**Issue by RalphBike** [calderacc/criticalmass-in#7]
The live tracking is not very intuitive to use with large crowds and many participants. The ride visualization should be more "snakey" to spot the ride easily.
Problems are:
-User icons are quite big, the whole screen is filled with some icons and the real mass is difficult to find. More or less only the accumulating icon shadows are a good indicator to find the mass.
-Lots of "wrong" icons are displayed, caused by people sending their position but not participating in the ride.

I suggest:
-Smaller marker for participants with a shadow. a small plain circle or dot with a shadow should be enough. 
-Less shadow for a single sender. Maybe colored shadow for better contrast to the background map?
-Less colorful maptiles for improved contrast
-Filtering for displayed participants. Wrong senders should be hidden. They could be identified like this:
--Wrong senders have not moved more than x meters in the last y seconds. 
--Wrong senders have only a small number x of other senders close to them (distance of y meters), when the number of participants for a town is higher than z.
-Hidden senders should automatically be displayed again once they behave in a plausible way.
-Heat map or other kind of visualisation that makes it easier to find masses of people rather than single senders.

**Comment by RalphBike** [comment]
![bildschirmfoto_2017-05-26_20-41-55-crop](https://cloud.githubusercontent.com/assets/17691743/26519502/56575fdc-42c2-11e7-8370-48e7f69d3063.png)

**Comment by RalphBike** [comment]
No news? Any chance to get an update before next last friday?

**Comment by maltehuebner** [comment]
@RalphBike I can do all the css stuff until Fahrradfreitag, but there’s no chance to filter all those items since that is a bigger issue.

**Comment by RalphBike** [comment]
Yeah, go go go!

PS: A bird in the hand is worth two in the bush.

**Comment by RalphBike** [comment]
From FB.com/cmhh:

KW: Hat bei mir diesmal nicht geklappt - 15 Punkte in ganz Hamburg verteilt. Das waren wohl die Aussteiger, denen es zu nass geworden ist. ;-) Habe es dann aber dank Live Ticker per Telegram (ähnl. WhatsApp) doch noch geschafft die Gruppe zu erreichen!

AH: Nein leider nicht hatte zwar die criticalmaps app an war aber eher schwer zu sehen wo die Mass her ging.

KW: hatte es auch damit versucht, aber es hat sich kein Grüppchen gezeigt, sondern nur vereinzelte Punkte über ganz Hamburg verteilt. Habe dann von einem Mitfahrer direkt Hilfe bekommen - er hat mir die jeweiligen Standorte gesimst.

**Comment by maltehuebner** [comment]
Nachdem das Tracking nur noch direkt über Critical Maps funktioniert, mache ich hier mal dicht.
